alias zshconfig="nvim ~/.zshrc"
alias ws="cd ~/workspace"
alias repo="cd ~/workspace/repo"
alias dc="git reset --hard"
alias st="git stash"
alias ust="git stash pop"
alias df="git diff"
alias dff="git diff --staged"
alias a="git add --all"
alias ua="git reset HEAD~"
alias ss="git status"
alias m="git checkout master"
alias b="git checkout"
alias squash="git rebase -i master"
alias python="/opt/homebrew/bin/python3"
alias v="nvim"
alias lg="lazygit"
alias ld="lazydocker"
# set NVIM_APPNAME to nvim-kickstart
# https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#FAQ
alias nvim-kickstart='NVIM_APPNAME="nvim-kickstart" nvim'