config:
  # MD013/line-length: Line length
  # Disabled: Hard to maintain with URLs and tables; modern editors wrap text.
  MD013: false

  # MD041/first-line-heading/first-line-h1: First line in a file should be a top-level heading
  # Disabled: Files often start with HTML comments (frontmatter) or badges.
  MD041: false

  # MD033/no-inline-html: Inline HTML
  # Disabled: HTML is often needed for advanced formatting (e.g., centering, complex tables).
  MD033: false

  # MD029/ol-prefix: Ordered list item prefix
  # Disabled: Allows '1. 1. 1.' style which is easier to reorder than '1. 2. 3.'
  MD029: false
